### ISSUE TITLE
[Tech]: Update dev enviromnent Karura parachain version

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-parachain#107]
### Problem statement

Current version 2.11 is outdated
Version 2.18 should be used (https://github.com/AcalaNetwork/Acala/tree/release-karura-2.18.0)

### Definition of Done

1. Karura with version 2.18 is used

Aha! Link: https://soramitsucoltd.aha.io/features/SKP-8

**Comment by Tieumsan** [comment]
@N1ghtStorm what should we do with this task ?
cc. @vovac12 @Cre-eD
