### ISSUE TITLE
[Tech]: Open HRMP Channel With Assethub on Rococo

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-parachain#125]
### Problem statement

Reserch how is it possible to establish HRMP channel via governance on Rococo

### Definition of Done

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] The HRMP channels 1000 -> 2011 and 2011 -> 1000 are established
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://soramitsucoltd.aha.io/features/SKP-7

**Comment by bgodlin** [comment]
Guide: https://substrate.stackexchange.com/questions/9699/inquiry-regarding-establishing-hrmp-channel-between-parachain-and-asset-hub-in-r/9729#9729
