### ISSUE TITLE
[Tech]: Implement Technical Committee (Governance)

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#129]
### Problem statement

We currently don't have any governance body on the Kusama parachain. We need to implement the same bodies as we have on the mainnet to manage governance operations on the network.

### Definition of Done

- [ ] Technical committee implemented the same way as on mainnet

**Comment by bgodlin** [comment]
Has to be checked for duplication with https://github.com/sora-xor/sora2-parachain/issues/127

**Comment by bgodlin** [comment]
Duplicate of #127
