### ISSUE TITLE
[Tech]: Implement XOR as native currency for the parachain

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#130]
### Problem statement

We currently don't have any token on the parachain. We need to add support of the XOR on the parachain, to do governance.

### Description

We should enable transfers of XOR from the mainnet to the SORA Kusama parachain. 
XOR should be the native currency on the parachain. 

### Definition of Done

- [ ] XOR as native currency on the parachain
- [ ] Migration to burn UNIT tokens from governance members (exclude collators' account from the migration)

**Comment by pg-vlad** [comment]
XOR as native currency: Sora Collator dev / Sora Collator stage
