### ISSUE TITLE
[Feature]: Enablement of `XOR`

### ISSUE THREAD

**Issue by bgodlin** [sora-xor/sora2-parachain#133]
### As a

TBA

### I want to

TBA

### So that

TBA

**Comment by Tieumsan** [comment]
@bgodlin how is it different from https://github.com/sora-xor/sora2-parachain/issues/130 ?

Please check and sync when creating new issues to avoid multiplying the number of issues on the board.

**Comment by bgodlin** [comment]
> @bgodlin how is it different from #130 ?
> 
> Please check and sync when creating new issues to avoid multiplying the number of issues on the board.

No difference. Duplicates #130.
