### ISSUE TITLE
Add SORA assets to SORA Parachain

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#17]
1. Start with Rococo
2. When successful, repeat on Kusama

### SORA assets

Asset Name: SORA
Asset Symbol:  XOR
Decimals:  18
existentialDeposit: 0
Multilocation: Don't use yet

Asset Name: Polkaswap
Asset Symbol:  PSWAP
Decimals:  18
existentialDeposit: 0
Multilocation: Don't use yet

Asset Name:  SORA Validator Token
Asset Symbol:  VAL
Decimals:  18
existentialDeposit: 0
Multilocation: Don't use yet

Asset Name:  SORA Synthetics
Asset Symbol:  XST
Decimals:  18
existentialDeposit: 0
Multilocation: Don't use yet

Asset Name:  SORA Synthetic USD
Asset Symbol:  XSTUSD
Decimals:  18
existentialDeposit: 0
Multilocation: Don't use yet

Aha! Link: https://soramitsucoltd.aha.io/features/SKP-14

**Comment by Tieumsan** [comment]
@N1ghtStorm I guess we can close this task, right ?

@bgodlin we'll need to add the technical description of our tokens to the wiki

**Comment by Tieumsan** [comment]
@N1ghtStorm please complete the list w/ Multilocation

**Comment by N1ghtStorm** [comment]
we propose to make multilocations with this pattern: { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: SORA_ASSET_ID}} ]}}

**Comment by N1ghtStorm** [comment]
Asset Name: SORA
Asset Symbol: XOR
Decimals: 18
existentialDeposit: 0
Multilocation:  { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: 0x020000000000000000000000000000000000000000000000000000000000000}} ]}}

Asset Name: Polkaswap
Asset Symbol: PSWAP
Decimals: 18
existentialDeposit: 0
Multilocation: { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: 0x0200050000000000000000000000000000000000000000000000000000000000}} ]}}

Asset Name: SORA Validator Token
Asset Symbol: VAL
Decimals: 18
existentialDeposit: 0
Multilocation: { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: 0x0200040000000000000000000000000000000000000000000000000000000000}} ]}}

Asset Name: SORA Synthetics
Asset Symbol: XST
Decimals: 18
existentialDeposit: 0
Multilocation: { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: 0x0200090000000000000000000000000000000000000000000000000000000000}} ]}}

Asset Name: SORA Synthetic USD
Asset Symbol: XSTUSD
Decimals: 18
existentialDeposit: 0
Multilocation: { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: 0x0200080000000000000000000000000000000000000000000000000000000000}} ]}}

**Comment by bgodlin** [comment]
> we propose to make multilocations with this pattern: { parents: 1, interior: { X2: [ {Parachain: 2011}, {GeneralKey: { length: 32, data: SORA_ASSET_ID}} ]}}

Is it a customisation?
