### ISSUE TITLE
[Bug]: Fix chainspec problem on the Kusama Parachain

### ISSUE THREAD

**Issue by N1ghtStorm** [sora-xor/sora2-parachain#174]
### Preconditions

Error: Input("\"Error parsing spec file: missing field beefy at line 55 column 13\"")

### Steps to reproduce

Kusama Parachain

### Actual behavior

Nodes with current version does not start

### Expected behavior

Node start properly

### Environment

{"label"=>"Production"}

**Comment by Tieumsan** [comment]
@N1ghtStorm @vovac12 what is the status of this issue ?
