### ISSUE TITLE
[Tech]: Change asset precision to 18

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#179]
### Problem statement

The assets on the parachain currently have a precision of 12. We want to implement the same precision as on the mainnet: 18.

### Definition of Done

- [ ] Asset precision changed to 18

**Comment by pg-vlad** [comment]
api.registry.chainDecimals Sora Collator dev is 18
api.registry.chainDecimals Sora Collator stage is 18
