### ISSUE TITLE
SORA mainnet --> Other parachains asset transfer

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#18]
As a **user** I want to **transfer/teleport my assets from the SORA parachain to other supported parachains through HRMP** so that **I can use my SORA assets on other parachains**.

**Comment by bgodlin** [comment]
Most likely there will be no entity as an `asset` on the parachain. Therefore, once user executes the teleport, one shouldn't even understand that the message went through the parachain

**Comment by bgodlin** [comment]
Tested only in private environment. Need to be treated separately for each new integrated parachain.
