### ISSUE TITLE
[SPIKE] Bridge SORA Mainnet <-> SORA Parachain

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#33]
What do other projects use ?

Common solution - Parity bridge ?

**Update doc:** https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/2213347329/Substrate+-+Relay-chain+bridge 

Update with sora network—sora kusama parachain bridge

parity bridge commons pallet

**Study:** https://github.com/paritytech/parity-bridges-common 

Investigate what networks use this

**3 cases:**
- asset created on the sora network, move it back and forth to the kusama parachain
- asset created on the sora kusama parachain and move it back and forth to the sora network
- asset created on another network and moved to the sora kusama parachain via xcm and move it back and forth to the sora network (**highest priority**)

**Comment by N1ghtStorm** [comment]
https://soramitsu.atlassian.net/wiki/spaces/PLS/pages/3700490241/Substrate+-+Parachain+Bridge
