### ISSUE TITLE
[Spike]: Add SORA to the list of parachains on DeFi website

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#42]
### Problem Statement
We have a Kusama parachain producing blocks and connected to the Kusama ecosystem. We want people to be able to see that we are part of the ecosystem.
For that reason, we need to investigate on which websites we should be referenced so that users could easily find us.

### Definition of Done
1. Build a list of website that we want to be referenced on
2. Send information to the websites from the list so that they can add us to the list of parachain

### Methodology
- Research DeFi websites
- Gather parachain information
- Communicate to website teams

### Useful resources
https://defillama.com/chains/Parachain

Aha! Link: https://soramitsucoltd.aha.io/features/SKP-13

**Comment by bgodlin** [comment]
TVL and MC will most likely always be empty, as the parachain will only be used as a proxy
