### ISSUE TITLE
[Investigation]: Parachain Block Production

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#59]
### Problem statement

Our parachain on Rococo stopped producing blocks. We need to investigate the reason why and fix it.
We need our parachain to produce blocks to be able to communicate with the Kusama ecosystem on Rococo (testnet).

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.parachain-collator-1.c1.stg1.sora2.soramitsu.co.jp#/explorer

According to the DevOps team, the reason is that our collator stopped producing blocks.

### Definition of Done

- Root cause of the block production stop identified
- Proposed solution to fix it established

### Methodology

- Investigate the parachain collators
- Investigate the parachain code
- Ask xDimon if help/info is required on the parachain
- Ask the DevOps team if info is required on the health of the parachain

**Comment by Harrm** [comment]
The collator fails every time with
[Parachain] Block import error: State Database error: Too many sibling blocks inserted    
and there's an open issue for that in cumulus repo
https://github.com/paritytech/cumulus/issues/432
which states that this problem can be mitigated by using revert command to discard the piled up leaves, after which the block production should continue normally (until this problem occurs again, at least).

However, revert command doesn't work, yielding 
2022-11-10 16:00:33.828  INFO                 main sc_service::chain_ops::revert_chain: There aren't any non-finalized blocks to revert.

Continuing investigation.

**Comment by mn13** [comment]
Hey, Sora team!
We have the same `Too many sibling` error on Equilibrium in moonbase-alphanet, catch in twice after runtime upgrade.
Our setup:
- 3 collators with polkadot-v0.9.24 version of substrate and cumulus, release-v0.9.24 of polkadot, the same version on wasm and binary
- Alphanet relaychain has 20 validators, they use westend with spec version  0.9.31
- Error occurs right after `parachainSystem->enactAuthorizedUpgrade` extrinsic

We tried to revert blocks and had the same result, chain doesn't revive. Also we resynced collators with no effect. Now we try to up new collators with new binary on polkadot-v0.9.29 version of substrate/cumulus/polkadot.

Log
```
2022-11-17 07:20:06 [Equilibrium] Failed to collect collation info. error=Application(UnknownBlock("Header was not found in the database: 0x37316b45935f53485269564f06eae2727644814e009fb392f9fc2282944811f1"))

2022-11-17 07:20:06 [Equilibrium] Block import error: State Database error: Too many sibling blocks inserted

2022-11-17 07:20:06 [Equilibrium] Error with block built on 0x6046a828901cb1623e28ca5c659151ef4682ef701fb6fe36fe555ec552227ae7: Import failed: State Database error: Too many sibling blocks inserted
```

Also looks like https://github.com/paritytech/cumulus/pull/1559 will fix https://github.com/paritytech/cumulus/issues/432 and it close to merge

**Comment by N1ghtStorm** [comment]
Created a task https://github.com/paritytech/subport/issues/529

**Comment by N1ghtStorm** [comment]
> Created a task [paritytech/subport#529](https://github.com/paritytech/subport/issues/529)

it looks like on previous issue our parachain has been just updated as parachain slot after it has been downgraded to parathread, without onboarding it with new genesis
https://github.com/paritytech/subport/issues/400

I created a new task:
https://github.com/paritytech/subport/issues/539
