### ISSUE TITLE
[DevOps]: Metrics - Parachain Health Monitoring

### ISSUE THREAD

**Issue by Tieumsan** [sora-xor/sora2-parachain#70]
### Problem statement

We want to determine the set of metrics to monitor the health of the parachain.

### Description

We want to communicate with the DevOps team to determine a set of metrics to monitor the health of the parachain(s).

We have a Telegram group with other participants of the Dotsama ecosystem to define a set of metrics for solo chains, relay chains, and parachains. We can use this chat to help defining the set of metrics.

### Definition of Done

- [ ] Determine the metrics to monitor the health of the parachain
- [ ] Determine the data sources to feed the metrics

**Comment by f33r0** [comment]
done a long time ago.
https://grafana.soramitsu.co.jp/d/vnoRKpl4z/sora2-parachain?orgId=1
We have already identified problems this way. Monitoring works for several months.
